"""
summarize_report.py
Reads tests/reports/latest.json (from pytest-json-report) and writes:
  - tests/reports/summary.md  (committed to repo, human-readable)
  - $GITHUB_STEP_SUMMARY       (shown in the Actions UI run page)
"""

import html
import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path

REPORT_PATH = Path("tests/reports/latest.json")
SUMMARY_PATH = Path("tests/reports/summary.md")

STATUS_EMOJI = {
    "passed":  "✅",
    "failed":  "❌",
    "skipped": "⏭️",
    "error":   "💥",
    "xfailed": "⚠️",
    "xpassed": "⚠️",
}


def load_report() -> dict:
    with open(REPORT_PATH) as f:
        return json.load(f)


# A bare Playwright/JS stack frame line, e.g. "at UtilityScript.<anonymous> (<anonymous>:1:44)"
_STACK_FRAME_RE = re.compile(r"^at\s+\S+\s+\(.*:\d+:\d+\)$")
# Our own check-failure detail lines, e.g. "[text_present] Pattern '...' not found. Got: ..."
_CHECK_DETAIL_RE = re.compile(r"^\[\w+\]")


def extract_detail(longrepr: str) -> str:
    """
    Pull the most useful single line out of a pytest longrepr.

    Prefers our own "[check_type] ..." failure details (last one wins, since
    that's the most specific). Otherwise prefers the first "E " line that
    isn't a bare stack frame (the actual exception message), falling back to
    the first/last "E " line if nothing better is found.
    """
    e_lines = []
    for line in longrepr.splitlines():
        stripped = line.strip()
        if stripped == "E" or stripped.startswith("E "):
            e_lines.append(stripped[1:].strip())

    if not e_lines:
        non_empty = [l.strip() for l in longrepr.splitlines() if l.strip()]
        return non_empty[-1] if non_empty else ""

    check_details = [l for l in e_lines if _CHECK_DETAIL_RE.match(l)]
    if check_details:
        return check_details[-1]

    non_stack = [l for l in e_lines if not _STACK_FRAME_RE.match(l)]
    return non_stack[0] if non_stack else e_lines[0]


def slug_from_node_id(node_id: str) -> str:
    """Extract the bookmarklet slug from a pytest node id."""
    # node_id looks like: tests/test_bookmarklets.py::test_bookmarklet[airbnb-user-bookmarklet]
    if "[" in node_id:
        return node_id.split("[", 1)[1].rstrip("]")
    return node_id


def build_markdown(report: dict) -> str:
    summary = report.get("summary", {})
    created = report.get("created", 0)
    duration = report.get("duration", 0)
    timestamp = datetime.fromtimestamp(created, tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    total   = summary.get("total", 0)
    passed  = summary.get("passed", 0)
    failed  = summary.get("failed", 0)
    skipped = summary.get("skipped", 0)
    error   = summary.get("error", 0)

    health_pct = int((passed / max(total - skipped, 1)) * 100)

    lines = [
        "# 🔍 Bookmarklet Health Report",
        "",
        f"**Generated:** {timestamp}  ",
        f"**Duration:** {duration:.1f}s  ",
        f"**Health:** {health_pct}% ({passed} passed / {failed} failed / {skipped} skipped / {error} errors)",
        "",
        "<table>",
        "<tr><th>Status</th><th>Bookmarklet</th><th>Detail</th></tr>",
    ]

    tests = report.get("tests", [])
    # Sort: failed first, then passed, then skipped
    order = {"failed": 0, "error": 1, "passed": 2, "skipped": 3, "xfailed": 4, "xpassed": 5}
    tests_sorted = sorted(tests, key=lambda t: order.get(t.get("outcome", ""), 99))

    for test in tests_sorted:
        outcome = test.get("outcome", "unknown")
        emoji = STATUS_EMOJI.get(outcome, "❓")
        slug = slug_from_node_id(test.get("nodeid", ""))

        # Pull failure message if present
        detail = ""
        call = test.get("call", {})
        if call and call.get("longrepr"):
            detail = extract_detail(call["longrepr"])[:200]

        # For skipped tests, grab the skip reason
        if outcome == "skipped":
            setup = test.get("setup", {})
            skip_msg = setup.get("longrepr", "")
            if isinstance(skip_msg, list):
                skip_msg = skip_msg[-1] if skip_msg else ""
            detail = str(skip_msg).replace("Skipped: ", "")[:200]

        detail = html.escape(detail)
        lines.append(
            f'<tr><td>{emoji} {outcome}</td><td><code>{html.escape(slug)}</code></td>'
            f'<td style="white-space:normal;word-break:break-word;max-width:500px;">{detail}</td></tr>'
        )

    lines.append("</table>")

    lines += [
        "",
        "---",
        f"*Auto-generated by [bookmarklet_health.yml](/.github/workflows/bookmarklet_health.yml)*",
    ]

    return "\n".join(lines)


def main():
    if not REPORT_PATH.exists():
        print(f"Report not found at {REPORT_PATH}")
        return

    report = load_report()
    markdown = build_markdown(report)

    SUMMARY_PATH.parent.mkdir(parents=True, exist_ok=True)
    SUMMARY_PATH.write_text(markdown)
    print(f"Wrote summary to {SUMMARY_PATH}")

    # Write to GitHub Actions step summary if running in Actions
    step_summary = os.environ.get("GITHUB_STEP_SUMMARY")
    if step_summary:
        with open(step_summary, "w") as f:
            f.write(markdown)
        print("Wrote to GITHUB_STEP_SUMMARY")

    # Print to stdout too
    print("\n" + markdown)


if __name__ == "__main__":
    main()