"""
summarize_report.py
Reads tests/reports/latest.json (from pytest-json-report) and writes:
  - tests/reports/summary.md  (committed to repo, human-readable)
  - $GITHUB_STEP_SUMMARY       (shown in the Actions UI run page)
"""

import json
import os
from datetime import datetime, timezone
from pathlib import Path

REPORT_PATH = Path("tests/reports/latest.json")
SUMMARY_PATH = Path("tests/reports/summary.md")

STATUS_EMOJI = {
    "passed":  "✅",
    "failed":  "❌",
    "skipped": "⏭️",
    "error":   "💥",
    "xfailed": "⚠️",
    "xpassed": "⚠️",
}


def load_report() -> dict:
    with open(REPORT_PATH) as f:
        return json.load(f)


def slug_from_node_id(node_id: str) -> str:
    """Extract the bookmarklet slug from a pytest node id."""
    # node_id looks like: tests/test_bookmarklets.py::test_bookmarklet[airbnb-user-bookmarklet]
    if "[" in node_id:
        return node_id.split("[", 1)[1].rstrip("]")
    return node_id


def build_markdown(report: dict) -> str:
    summary = report.get("summary", {})
    created = report.get("created", 0)
    duration = report.get("duration", 0)
    timestamp = datetime.fromtimestamp(created, tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    total   = summary.get("total", 0)
    passed  = summary.get("passed", 0)
    failed  = summary.get("failed", 0)
    skipped = summary.get("skipped", 0)
    error   = summary.get("error", 0)

    health_pct = int((passed / max(total - skipped, 1)) * 100)

    lines = [
        "# 🔍 Bookmarklet Health Report",
        "",
        f"**Generated:** {timestamp}  ",
        f"**Duration:** {duration:.1f}s  ",
        f"**Health:** {health_pct}% ({passed} passed / {failed} failed / {skipped} skipped / {error} errors)",
        "",
        "| Status | Bookmarklet | Detail |",
        "|--------|-------------|--------|",
    ]

    tests = report.get("tests", [])
    # Sort: failed first, then passed, then skipped
    order = {"failed": 0, "error": 1, "passed": 2, "skipped": 3, "xfailed": 4, "xpassed": 5}
    tests_sorted = sorted(tests, key=lambda t: order.get(t.get("outcome", ""), 99))

    for test in tests_sorted:
        outcome = test.get("outcome", "unknown")
        emoji = STATUS_EMOJI.get(outcome, "❓")
        slug = slug_from_node_id(test.get("nodeid", ""))

        # Pull failure message if present
        detail = ""
        call = test.get("call", {})
        if call and call.get("longrepr"):
            # Grab just the last line of the longrepr (the actual assertion message)
            longrepr = call["longrepr"]
            last_line = [l.strip() for l in longrepr.splitlines() if l.strip()]
            detail = last_line[-1][:120] if last_line else ""

        # For skipped tests, grab the skip reason
        if outcome == "skipped":
            setup = test.get("setup", {})
            skip_msg = setup.get("longrepr", "")
            if isinstance(skip_msg, list):
                skip_msg = skip_msg[-1] if skip_msg else ""
            detail = str(skip_msg).replace("Skipped: ", "")[:120]

        detail = detail.replace("|", "/")  # avoid breaking markdown table
        lines.append(f"| {emoji} {outcome} | `{slug}` | {detail} |")

    lines += [
        "",
        "---",
        f"*Auto-generated by [bookmarklet_health.yml](/.github/workflows/bookmarklet_health.yml)*",
    ]

    return "\n".join(lines)


def main():
    if not REPORT_PATH.exists():
        print(f"Report not found at {REPORT_PATH}")
        return

    report = load_report()
    markdown = build_markdown(report)

    SUMMARY_PATH.parent.mkdir(parents=True, exist_ok=True)
    SUMMARY_PATH.write_text(markdown)
    print(f"Wrote summary to {SUMMARY_PATH}")

    # Write to GitHub Actions step summary if running in Actions
    step_summary = os.environ.get("GITHUB_STEP_SUMMARY")
    if step_summary:
        with open(step_summary, "w") as f:
            f.write(markdown)
        print("Wrote to GITHUB_STEP_SUMMARY")

    # Print to stdout too
    print("\n" + markdown)


if __name__ == "__main__":
    main()