"""
test_bookmarklets.py
Runs health checks against every bookmarklet discovered on tools.myosint.training.
Each bookmarklet gets its own parametrized test case driven by its expectation file.

Check types supported:
  modal_appears      - A DOM element matching a selector (and optional text) is visible
  text_present       - An element matching selector contains text matching a pattern
  element_count      - At least min_count elements matching selector exist
  no_js_errors       - No uncaught JS exceptions were thrown during execution
  network_request    - At least one request to a URL pattern was made
  page_redirected    - The page URL changed to match a pattern after execution
"""

import json
import re
import time
import pytest
from pathlib import Path
from playwright.sync_api import Page, expect

REPORTS_DIR = Path(__file__).parent / "reports"
REPORTS_DIR.mkdir(exist_ok=True)

# Attribution text present in every myosint bookmarklet modal
UNIVERSAL_ATTRIBUTION = "Generated by a bookmarklet from https://tools.myosint.training"


# ── Helpers ───────────────────────────────────────────────────────────────────

def inject_and_run(page: Page, js_href: str, wait_ms: int = 2000):
    """
    Execute the bookmarklet JS in the page context.
    js_href is the raw href attribute value, e.g. "javascript:(function(){...})()"
    """
    # Strip the leading "javascript:" scheme
    js_code = js_href
    if js_code.startswith("javascript:"):
        js_code = js_code[len("javascript:"):]

    page.evaluate(js_code)
    page.wait_for_timeout(wait_ms)


def run_check(page: Page, check: dict, js_errors: list) -> tuple[bool, str]:
    """
    Execute a single check dict. Returns (passed: bool, message: str).
    """
    check_type = check.get("type")

    # ── modal_appears ─────────────────────────────────────────────────────────
    if check_type == "modal_appears":
        selector = check.get("selector", "div")
        text_contains = check.get("text_contains")
        try:
            if text_contains:
                locator = page.get_by_text(text_contains, exact=False)
                locator.wait_for(state="visible", timeout=5000)
                return True, f"Found text: '{text_contains}'"
            else:
                el = page.wait_for_selector(selector, state="visible", timeout=5000)
                return (True, f"Selector visible: {selector}") if el else \
                       (False, f"Selector not visible: {selector}")
        except Exception as e:
            return False, f"modal_appears failed: {e}"

    # ── text_present ──────────────────────────────────────────────────────────
    elif check_type == "text_present":
        selector = check.get("selector", "body")
        pattern = check.get("text_pattern")
        try:
            elements = page.query_selector_all(selector)
            if not elements:
                return False, f"No elements found for selector: {selector}"
            texts = [el.inner_text() for el in elements]
            combined = " ".join(texts)
            if pattern:
                if re.search(pattern, combined):
                    return True, f"Pattern '{pattern}' found in {len(elements)} elements"
                return False, f"Pattern '{pattern}' not found. Got: {combined[:200]}"
            return True, f"Elements present: {len(elements)}"
        except Exception as e:
            return False, f"text_present failed: {e}"

    # ── element_count ─────────────────────────────────────────────────────────
    elif check_type == "element_count":
        selector = check.get("selector")
        min_count = check.get("min_count", 1)
        try:
            elements = page.query_selector_all(selector)
            count = len(elements)
            if count >= min_count:
                return True, f"Found {count} elements (min: {min_count})"
            return False, f"Found {count} elements, expected at least {min_count}"
        except Exception as e:
            return False, f"element_count failed: {e}"

    # ── no_js_errors ──────────────────────────────────────────────────────────
    elif check_type == "no_js_errors":
        if js_errors:
            return False, f"JS errors detected: {'; '.join(js_errors)}"
        return True, "No JS errors"

    # ── network_request ───────────────────────────────────────────────────────
    elif check_type == "network_request":
        # This check is evaluated after inject_and_run; the caller pre-captures requests
        # Pass requests list via check dict (populated by test before calling run_check)
        url_pattern = check.get("url_pattern", "")
        requests = check.get("_captured_requests", [])
        matches = [r for r in requests if re.search(url_pattern, r)]
        if matches:
            return True, f"Network request matched '{url_pattern}': {matches[0]}"
        return False, f"No request matched pattern '{url_pattern}'. Saw: {requests[:5]}"

    # ── page_redirected ───────────────────────────────────────────────────────
    elif check_type == "page_redirected":
        url_pattern = check.get("url_pattern", "")
        current_url = page.url
        if re.search(url_pattern, current_url):
            return True, f"URL matched '{url_pattern}': {current_url}"
        return False, f"URL '{current_url}' did not match '{url_pattern}'"

    else:
        return False, f"Unknown check type: '{check_type}'"


# ── Main test ─────────────────────────────────────────────────────────────────

def test_bookmarklet(page: Page, bookmarklet: dict):
    """
    Health check for a single bookmarklet. Parametrized over all discovered tools.
    """
    slug         = bookmarklet["slug"]
    name         = bookmarklet["name"]
    js           = bookmarklet["js"]
    target_url   = bookmarklet.get("target_url", "")
    wait_ms      = bookmarklet.get("wait_ms", 2500)
    checks       = bookmarklet.get("checks", [])

    assert target_url, f"[{slug}] No target_url in expectation file"
    assert js,         f"[{slug}] No bookmarklet JS found on live page"

    # Capture JS errors
    js_errors = []
    page.on("pageerror", lambda err: js_errors.append(str(err)))

    # Capture network requests (for network_request checks)
    captured_requests = []
    page.on("request", lambda req: captured_requests.append(req.url))

    # Navigate to target
    page.goto(target_url, wait_until="domcontentloaded", timeout=30_000)
    page.wait_for_timeout(1500)  # let page settle

    # Run the bookmarklet
    inject_and_run(page, js, wait_ms=wait_ms)

    # ── Universal check: attribution badge should appear in every modal ───────
    # (skip for bookmarklets that redirect the page instead of showing a modal)
    has_redirect_check = any(c.get("type") == "page_redirected" for c in checks)
    if not has_redirect_check:
        try:
            page.get_by_text(UNIVERSAL_ATTRIBUTION, exact=False).wait_for(
                state="visible", timeout=5000
            )
        except Exception:
            pytest.fail(
                f"[{slug}] Universal attribution badge not found. "
                f"Expected text: '{UNIVERSAL_ATTRIBUTION}'"
            )

    # ── Per-tool checks ───────────────────────────────────────────────────────
    failures = []
    for check in checks:
        # Inject captured requests for network_request checks
        if check.get("type") == "network_request":
            check["_captured_requests"] = captured_requests

        passed, message = run_check(page, check, js_errors)
        if not passed:
            failures.append(f"  [{check.get('type')}] {message}")

    if failures:
        failure_report = "\n".join(failures)
        pytest.fail(f"[{slug}] {len(failures)} check(s) failed:\n{failure_report}")